# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, tag ]

services:
  docker:
    image: registry.fpfis.eu/fpfis/docker:18-dind
    privileged: true

pipeline:

  # Test image build.
  build:
    image: registry.fpfis.eu/fpfis/docker:18-dind
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - sleep 10
      - docker ps
      - docker build -t openeuropa/triple-store-dev .

  # Deploy image to Docker Hub.
  publish-docker-image:
    image: registry.fpfis.eu/drone-plugins/docker
    repo: openeuropa/triple-store-dev
    dockerfile: Dockerfile
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: [ push ]
      branch: master

  publish-docker-image-tag:
    image: registry.fpfis.eu/drone-plugins/docker
    repo: openeuropa/triple-store-dev
    dockerfile: Dockerfile
    tags:
      - ${DRONE_TAG}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: [ tag ]
      branch: master

  # Deploy image to Gitlab.
  publish-docker-image-gitlab:
    image: registry.fpfis.eu/drone-plugins/docker
    repo: registry.fpfis.eu/openeuropa/triple-store-dev
    dockerfile: Dockerfile
    secrets:
      - source: GITLAB_USERNAME
        target: DOCKER_USERNAME
      - source: GITLAB_PASSWORD
        target: DOCKER_PASSWORD
    when:
      event: [ push ]
      branch: master

  publish-docker-image-tag-gitlab:
    image: registry.fpfis.eu/drone-plugins/docker
    repo: registry.fpfis.eu/openeuropa/triple-store-dev
    dockerfile: Dockerfile
    tags:
      - ${DRONE_TAG}
    secrets:
      - source: GITLAB_USERNAME
        target: DOCKER_USERNAME
      - source: GITLAB_PASSWORD
        target: DOCKER_PASSWORD
    when:
      event: [ tag ]
      branch: master
