# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, tag ]

pipeline:

  # Test image build.
  build:
    image: git.fpfis.tech.ec.europa.eu/fpfis/dependency_proxy/containers/docker:18-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker ps
      - docker build -t openeuropa/triple-store-dev .

  # Deploy image to Docker Hub.
  publish-docker-image-tag:
    image: registry.fpfis.eu/drone-plugins/docker
    privileged: true
    repo: openeuropa/triple-store-dev
    dockerfile: Dockerfile
    tags:
      - latest
      - ${DRONE_TAG}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: [ tag ]
      branch: master

  # Deploy image to Gitlab.
  publish-docker-image-tag-gitlab:
    image: registry.fpfis.eu/drone-plugins/docker
    privileged: true
    repo: registry.fpfis.eu/openeuropa/triple-store-dev
    dockerfile: Dockerfile
    tags:
      - latest
      - ${DRONE_TAG}
    registry: registry.fpfis.eu
    secrets:
      - source: GITLAB_USERNAME
        target: DOCKER_USERNAME
      - source: GITLAB_PASSWORD
        target: DOCKER_PASSWORD
    when:
      event: [ tag ]
      branch: master
